In [6]:
import pandas as pd
df=pd.read_csv('vgsales.csv')
df  # df likhne se upar wala line execute hoga
df.shape#sirf last wala line execute hota hai

(16598, 11)

In [7]:
df.values
# x=df.drop(column=['ja jo likhaega wo hat jaega'])

array([[1, 'Wii Sports', 'Wii', ..., 3.77, 8.46, 82.74],
       [2, 'Super Mario Bros.', 'NES', ..., 6.81, 0.77, 40.24],
       [3, 'Mario Kart Wii', 'Wii', ..., 3.79, 3.31, 35.82],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.01],
       [16599, 'Know How 2', 'DS', ..., 0.0, 0.0, 0.01],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.01]],
      dtype=object)

In [17]:
##numpy
import numpy as np
a=np.array([1,2,3]) #we can lasa.o make multidimnesional array
a.ndim# mtlb kitna list hai basically



1

In [25]:
b=np.array([[1,2,3,4],[3,4,5,6],[8,9,5,8]])

In [26]:
##to get shape
b.shape

(3, 4)

In [27]:
#get typr
a.dtype

dtype('int32')

In [28]:
##get size
a.itemsize

4

In [30]:
#total size
b.nbytes

48

In [31]:
#to get specific element
b[1,-1]

6

In [32]:
# get specific row
b[0,:] #similarily we can do for column

array([1, 2, 3, 4])

In [34]:
b[0,1:-1:2]#natlab oth row ke pahle index se last index tak with a gap of 2
#we can also modify the element

array([2])

In [36]:
##all zero matrix
np.zeros((2,3))#can generate zero matrix of specified dimension
##np.ones(()) for generating identity matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
###any other matrix
np.full((2,2),66)

array([[66, 66],
       [66, 66]])

In [39]:
np.full_like(a,4)##3sized matrix me 4 likhna hai

array([4, 4, 4])

In [40]:
#random decimal no
np.random.rand(4,5)#print betweeen 0 and 1

array([[0.8288889 , 0.80311137, 0.95306548, 0.63885247, 0.8694288 ],
       [0.34055086, 0.3579562 , 0.67716129, 0.12327104, 0.05089288],
       [0.85863723, 0.53055559, 0.04518037, 0.60220738, 0.23704325],
       [0.36506481, 0.11504141, 0.85614115, 0.88210307, 0.54363134]])

In [46]:
##random integer value
np.random.randint(4,7,size=(3,4))#btween 4 to 7(ixcluded) of given size

array([[5, 4, 5, 6],
       [5, 6, 6, 5],
       [5, 4, 4, 6]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
##repeat an array 
ab=np.array([[1,2,3]])
ar=np.repeat(ab,3,axis=1)
print(ar)

[[1 1 1 2 2 2 3 3 3]]


In [58]:
#a programming
o=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
o[1:-1,1:-1]=z
print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
b=a.copy()

In [60]:
a+2
a-2
a*2
#we can do operation on the element directly
# similarily with all the different matric

array([3, 4, 5])

In [61]:
#if we use direct * sign for matrix multiplication then it will multiply row by row
# to actually multiply two matrix we use
# np.matmul(a,b) and they shoukd be compatible

14

In [63]:
##determinst od a matrix
c=np.identity(3)
np.linalg.det(c)
##some more direct libraries we can check out from google

1.0

##### statistics

In [67]:
stat=np.array([[5,2,3],[3,4,5]])
np.min(stat,axis=1)# axis o is downward axis
#axis 1 is horizontal axis

array([2, 3])

In [68]:
np.sum(stat,axis=1)## 1 matlab horizonatal row ka sum print krega

array([10, 12])

In [70]:
stt=stat.reshape((1,6))## we can redhape the matrix
print(stt)
#np.revel --isse 1d array banta hai
# np.arange(15)matalab 0 to 14 array dega
# l=np.linspace(1,5,4) matlab 1 to tak 4 random equally spaced no generate kregaa

[[5 2 3 3 4 5]]


In [74]:
# vertical stacking array
stu=np.array([[1,2,3],[4,5,6]])
np.stack([stat,stu])
# np.hstack
# np.vstack

array([[[5, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [4, 5, 6]]])